import { NextResponse } from 'next/server'

export async function GET(request: Request) {
	const projectsArray = [
		{
			id: 13,
			title: 'Soulsmith',
			framework: 'React',
			url: 'https://soulsmith.vercel.app/',
			github: 'https://github.com/asherman-ca/soulsmith',
			tools: ['React', 'Next.js', 'Supabase + Postgres', 'TailwindCSS'],
			description:
				'Social platform and gaming companion for Soulstone Survivors',
			items: [
				'Standard suite of social features - discovery, following, liking etc...',
				'SSR for SEO and inital page load performance',
				'Infinite scrolling & loading on discovery pages',
				'Url param sorting to improve UX on tablular data pages when navigating',
				'Robust relational database schema for optimal data storage and retrieval',
				'Subtle animations using Framer Motion for seemless UX',
				'Nextui for rapid prototyping and TailwindCSS for custom styling',
			],
			active: true,
		},
		{
			id: 12,
			title: 'Liquify',
			framework: 'React',
			url: 'https://liquify-three.vercel.app/',
			github: 'https://github.com/asherman-ca/liquify',
			tools: ['React', 'Next.js', 'Supabase + Postgres', 'TailwindCSS'],
			description: 'A Crypto-futures testnet trading simulator',
			items: [
				'Futures trading simulator with live data from public crypto API',
				'SSR for SEO and inital page load performance',
				'Live database-table subscriptions on client for post-SSR data fetching on update/insert/delete',
				'Server side liquidation engine on short interval (cron) for trade validation',
				'Watchlist (like) feature for tracking specific assets',
				'Subtle animations using Framer Motion for seemless UX',
				'Nextui for rapid prototyping and TailwindCSS for custom styling',
			],
			active: true,
		},
		{
			id: 11,
			title: 'Supper',
			framework: 'React',
			url: 'https://supper-eta.vercel.app/',
			github: 'https://github.com/asherman-ca/supper',
			tools: ['React', 'Next.js', 'mySQL', 'TailwindCSS'],
			description: 'A Job Search Tracker with AI CV Builder',
			items: [
				'SSR to improve SEO and performance',
				'ReactQuery for efficient data fetching and caching',
				'NextAuth for authentication and authorization',
				'End to End type safety and consistency using Zod + TypeScript inference',
				'OpenAi Vercel SDK for AI CV Builder',
				'Edge function for optimal handling of OpenAi data stream',
				'Subtle animations using Framer Motion for seemless UX',
				'DaisyUI for rapid prototyping and TailwindCSS for custom styling',
			],
			active: true,
		},
		{
			id: 10,
			title: 'Chonkify',
			framework: 'React',
			url: 'https://chonkify.vercel.app/',
			github: 'https://github.com/asherman-ca/chonkify',
			tools: [
				'React',
				'Next.js',
				'Stable Diffusion',
				'mySQL',
				'Firebase',
				'Stripe',
			],
			description: 'An AI image generator for pets',
			items: [
				'Best-in-class image model for image generation',
				'Data streaming for image responses for optimal UX',
				'Token system to manage user access to AI model',
				'SSR and client side rendering to improve SEO and performance',
				'Client side data caching using SWR for efficiency and dynamic invalidation',
				'Accessed multiple web services for image hosting, AI modeling, data storage and app hosting',
				'Edge function for optimal handling of large data stream from image model',
				'Subtle animations for seemless UX',
				'Fully responsive design with mobile first approach',
				'Handrolled modern ui components on top of Tailwind utility classes and HeadlessUI',
			],
			active: true,
		},
		{
			id: 9,
			title: 'Chonker',
			framework: 'React',
			url: 'https://chonker.vercel.app/',
			github: 'https://github.com/asherman-ca/chonker',
			tools: ['React', 'Next.js', 'Stable Diffusion', 'Replicate', 'mySQL'],
			description: 'An AI image generator for pets',
			items: [
				'Utilized Stable Diffusion and Replicate to generate images',
				'Implimented token system to manage user access to AI model',
				'Combined SSR and client side rendering to improve SEO and performance',
				'Client side data caching using SWR for efficiency and dynamic invalidation',
				'Accessed multiple web services for image hosting, AI modeling, data storage and app hosting',
				'Applied subtle animations for seemless UX',
				'Handrolled modern ui components on top of Tailwind utility classes and HeadlessUI',
			],
			active: true,
		},
		{
			id: 8,
			title: 'Tickr4',
			framework: 'React',
			url: 'https://tickr4.vercel.app/',
			github: 'https://github.com/asherman-ca/tickr4',
			tools: ['React', 'Next.js', 'NewsAPI', 'CoinGecko', 'NeonSQL'],
			description:
				'A crypto ticker, social network and testnet trading simulator',
			items: [
				'Combined SSR and client side rendering to improve SEO and performance',
				'Used incremental static regeneratiion on dynamic routes for optimal performance',
				'Accessed multiple public/free APIs to provide live data and news',
				'Applied subtle animations for seemless UX',
				'Handrolled modern ui components on top of Tailwind utility classes',
				'Calculated realized and unrealized PNL stats using order history and live prices',
			],
			active: true,
		},
		{
			id: 6,
			title: 'BuzzThing',
			framework: 'React',
			url: '',
			github: 'https://github.com/asherman-ca/infinilist',
			tools: ['React', 'Next.js', 'OpenAI', 'Pexels'],
			description: 'A generative site of entertaining listicles',
			items: [
				"Use OpenAI's GPT-3.5 model to generate consumable listicle content",
				'dynamic and efficient image queries to Pexels API to provide relevant images',
				'static site generation to improve performance, SEO and prevent unbound API expedeniture',
				'unhosted to due to cost of GPT-3.5 API and vercel hosting limitations',
			],
			active: false,
		},
		{
			id: 7,
			title: 'JobThing',
			framework: 'React',
			url: 'https://job-thing.vercel.app/',
			github: 'https://github.com/asherman-ca/jobThing',
			tools: [
				'React',
				'Next.js',
				'TypeScript',
				'Prisma',
				'PostgreSQL',
				'TailwindCSS',
			],
			items: [
				'100% Server Rendering for SEO and performance',
				'Full Next 13.4 utilization with 100% server component fetching/mutation',
				'Organizes job applications by job search and application status',
				'Handrolled modern ui components on top of Tailwind utility classes',
				'Subtle animations for optimal UX',
			],
			description: 'A job application tracker',
			active: true,
		},
		{
			id: 3,
			title: 'Miyagi',
			framework: 'React',
			url: 'https://miyagi.tech/',
			github: 'https://github.com/asherman-ca/miyagi',
			description: 'Social platform for discovering and sharing content',
			tools: ['React', 'Firebase', 'Bootstrap'],
			items: [
				'Enabled content discovery with search features',
				`Provided content interaction with 'like' and 'follow' features`,
				'Enriched post content with YouTube and Instagram embedding',
				'Structured css to allow seamless cross-platform UX',
			],
			active: true,
		},
		{
			id: 4,
			title: 'MyOnlinePool',
			framework: 'React',
			url: '',
			github: 'https://github.com/davidhu2000/myonlinepool',
			tools: ['React', 'Rails', 'SQL'],
			description: 'Social platform for competitive NFL brackets',
			items: [
				"Updated score data through queries to the NFL's api",
				'Processed payment through hand rolled PayPal implementation',
				'Utilized React to implement a responsive and modular frontend user experience',
			],
			active: false,
		},
		{
			id: 5,
			title: 'EZ Streaming',
			framework: 'React',
			url: '',
			github: 'https://github.com/davidhu2000/eezee',
			tools: ['React-Native', 'Firebase'],
			description: 'Live database for discovering streaming locations',
			items: [
				"Created a cohesive UI using React-native's integrated styling attributes",
				'Queried GuideBox API to access multiple services in a single API call and reduce backend complexity',
			],
			active: false,
		},
	]

	return NextResponse.json({ projects: projectsArray })
}
